### ISSUE TITLE
GCC 12 requires utility to be included for std::exchange

### ISSUE THREAD

**Issue by ineedbots** [Brandon-T/RemoteInput#2]
![image](https://user-images.githubusercontent.com/751729/176283289-c4e99221-bb05-4258-8437-c1ac9c0de169.png)

![image](https://user-images.githubusercontent.com/751729/176283244-6f1f5bf7-3d34-4d4e-924f-09bbac9c6e2a.png)

Refer to: https://github.com/doxygen/doxygen/issues/8909#issuecomment-1120165358

Build is broken while using GCC v12. A fix is by inserting `include <utility>` to locations that use std::exchange.
![image](https://user-images.githubusercontent.com/751729/176283044-bb778e8f-2e4f-421f-8bde-8e01bb1398b8.png)

**Comment by rojii** [comment]
she was more like a beauty queen
